// This file is autogenerated -- run parseExercises.js to update
import React from 'react';
import { RouteComponentProps } from "react-router-dom";
import styled from 'styled-components';

const Wrapper = styled.div`
  max-width: 1000px;
  margin: auto;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-column-gap: 25px;
  grid-row-gap: 25px;
`;

const Exercise = styled.div`
  padding: 10px;
  border-radius: 5px;
  box-shadow: 0 0 5px 5px rgba(204,204,204,0.24);
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);
  display: flex;
  flex-direction: column;
  &:hover {
    cursor: pointer;
    box-shadow: 0 0 10px 10px rgba(204,204,204,0.33);
  }
`;

const Title = styled.div`
  grid-column: 1 / span 4;
  display: flex;
  font-weight: bold;
  font-size: 30px;
  border-bottom: 1px solid #eaeaea;
  margin-top: 10px;
`;

const Number = styled.span`
  font-size: 2rem;
  font-weight: 700;
`;

const Home: React.FC<RouteComponentProps> = ({ history }) => {
    return (
        <Wrapper>
              SUp
 
        </Wrapper>
    )
};

export default Home;
