// This file is autogenerated -- run parseExercises.js to update
import React from 'react';
import { RouteComponentProps } from "react-router-dom";
import styled from 'styled-components';

const Wrapper = styled.div`
  max-width: 1000px;
  margin: auto;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-column-gap: 25px;
  grid-row-gap: 25px;
`;

const Exercise = styled.div`
  padding: 10px;
  border-radius: 5px;
  box-shadow: 0 0 5px 5px rgba(204,204,204,0.24);
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);
  display: flex;
  flex-direction: column;
  &:hover {
    cursor: pointer;
    box-shadow: 0 0 10px 10px rgba(204,204,204,0.33);
  }
`;

const Title = styled.div`
  grid-column: 1 / span 4;
  display: flex;
  font-weight: bold;
  font-size: 30px;
  border-bottom: 1px solid #eaeaea;
  margin-top: 10px;
`;

const Number = styled.span`
  font-size: 2rem;
  font-weight: 700;
`;

const Home: React.FC<RouteComponentProps> = ({ history }) => {
    return (
        <Wrapper>
            <Title>React fundamentals</Title>
            <Exercise onClick={() => history.push("/exercise/1")}>
                <Number>1</Number>
                <div> hello world component</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/2")}>
                <Number>2</Number>
                <div> using typescript</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/3")}>
                <Number>3</Number>
                <div> car info component</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/4")}>
                <Number>4</Number>
                <div> click alert</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/5")}>
                <Number>5</Number>
                <div> click counter</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/6")}>
                <Number>6</Number>
                <div> favorite color</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/7")}>
                <Number>7</Number>
                <div> clock component</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/8")}>
                <Number>8</Number>
                <div> framework statistics</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/9")}>
                <Number>9</Number>
                <div> service status</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/10")}>
                <Number>10</Number>
                <div> user form</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/11")}>
                <Number>11</Number>
                <div> conversion m ft</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/12")}>
                <Number>12</Number>
                <div> theme provider</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/13")}>
                <Number>13</Number>
                <div> counter error boundary</div>
            </Exercise>
<Title>Styled components</Title>
            <Exercise onClick={() => history.push("/exercise/14")}>
                <Number>14</Number>
                <div> styled button</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/15")}>
                <Number>15</Number>
                <div> styled button props</div>
            </Exercise>
<Title>React router</Title>
            <Exercise onClick={() => history.push("/exercise/16")}>
                <Number>16</Number>
                <div> routes</div>
            </Exercise>

            <Exercise onClick={() => history.push("/exercise/17")}>
                <Number>17</Number>
                <div> routes active style</div>
            </Exercise>
        </Wrapper>
    )
};

export default Home;
